menu4you/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
from . import views

handler404 = "menu4you.views.handler404"
urlpatterns = [

    # Home Page
    url(r'^$', views.index),
    url(r'^about/$', views.about),
    url(r'^send-mail/$', views.send_mail_view),
    url(r'^projects/mobile-terminal/$', views.mobile_terminal),
    url(r'^projects/waiter-terminal/$', views.waiter_terminal),
    url(r'^projects/mobile-menu/$', views.mobile_menu),

    # Admin panel
    url(r'^admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/models.py
from django.db import models
from sorl.thumbnail import ImageField


# Главная страница

class HomePage(models.Model):


    class Meta:
        verbose_name = "Главная"
        verbose_name_plural = "Главная"


    email = models.CharField("Email для обратной связи",
                             max_length=200, blank=True)
    price = models.CharField("Цена", max_length=200, blank=True)
    video_url = models.CharField("Видео", blank=True, max_length=200)

    # Section 1

    section1_header  = models.CharField("Заголовок", max_length=200)
    section1_q1 = models.CharField("Вопрос 1", max_length=200, blank=True)
    section1_q2 = models.CharField("Вопрос 2", max_length=200, blank=True)
    section1_q3 = models.CharField("Вопрос 3", max_length=200, blank=True)
    section1_promo = models.TextField("Текст акции", blank=True)
    section1_footer = models.TextField("Футер", blank=True)

    # Section 2

    section2_l_text = models.TextField("Текст слева", blank=True)
    section2_r_text = models.TextField("Текст справа", blank=True)
    section2_footer = models.TextField("Футер", blank=True)

    # Section 3

    section3_l_text = models.TextField("Текст слева", blank=True)
    section3_r_text = models.TextField("Текст справа", blank=True)
    section3_footer = models.TextField("Футер", blank=True)

    # Our Team

    team_header = models.CharField("Заголовок", max_length=200)
    team_text = models.TextField("Текст", blank=True)


# О проекте

class AboutPage(models.Model):


    class Meta:
        verbose_name = "О проекте"
        verbose_name_plural = "О проекте"


    goal = models.TextField("Наша цель", blank=True)


# Мобильный терминал менеджера

class MobileManagerProject(models.Model):


    class Meta:
        verbose_name = "Мобильный терминал менеджера"
        verbose_name_plural = "Мобильный терминал менеджера"


    # Main
    email = models.CharField("Email для обратной связи",
                             max_length=200, blank=True)
    price = models.CharField("Цена", max_length=200, blank=True)

    # Screen 1
    screen1_header = models.CharField("Заголовок", max_length=200)
    screen1_text = models.TextField("Текст", blank=True)

    # Screen 2
    screen2_header = models.CharField("Заголовок", max_length=200)
    screen2_text = models.TextField("Текст", blank=True)

    # Screen 3
    screen3_header = models.CharField("Заголовок", max_length=200)
    screen3_text = models.TextField("Текст", blank=True)

    # Screen 4
    screen4_header = models.CharField("Заголовок", max_length=200)
    screen4_text = models.TextField("Текст", blank=True)


# Мобильный терминал официанта

class WaiterTerminalProject(models.Model):


    class Meta:
        verbose_name = "Мобильный терминал официанта"
        verbose_name_plural = "Мобильный терминал официанта"


    # Main
    email = models.CharField("Email для обратной связи",
                             max_length=200, blank=True)
    price = models.CharField("Цена", max_length=200, blank=True)
    video_url = models.CharField("Видео", blank=True, max_length=200)

    # Screen 1
    screen1_header = models.CharField("Заголовок", max_length=200)
    screen1_quote = models.TextField("Цитата", blank=True)
    screen1_u_quote = models.TextField("Под цитатой", blank=True)
    screen1_text = models.TextField("Текст", blank=True)


class WaiterSlide(models.Model):


    class Meta:
        verbose_name = "Слайд"
        verbose_name_plural = "Слайды"


    parent = models.ForeignKey(WaiterTerminalProject)
    header = models.CharField("Заголовок", max_length=200)
    text = models.TextField("Текст", blank=True)
    image = ImageField("Изображение", null=True)

# Меню на планшете

class TabletMenuProject(models.Model):


    class Meta:
        verbose_name = "Меню на планшете"
        verbose_name_plural = "Меню на планшете"


    # Main
    email = models.CharField("Email для обратной связи",
                             max_length=200, blank=True)
    price   = models.CharField("Цена", max_length=200, blank=True)
    video_url = models.CharField("Видео", blank=True, max_length=200)


class TabletSlide (models.Model):


    class Meta:
        verbose_name = "Слайд"
        verbose_name_plural = "Слайды"


    parent = models.ForeignKey(TabletMenuProject)
    header = models.CharField("Заголовок", max_length=200)
    text = models.TextField("Текст", blank=True)
    image = ImageField("Изображение")

templates/about.html
{{ header }}
{{ menu }}


<div class="about-top-parralax-wrapper">
    <div class="top-parralax-bg parallax-background" parallax-ratio="0.4"></div>
</div>

<div id="about-sector">
    <h1>О проекте</h1>
    <p class="our-target">{{ content.goal|linebreaksbr }}</p>

    <div class="gears">

        <!-- Left -->

        <div class="gear-content" id="about-gear-1">
            <h2>Сайты доставки</h2>
            <h3>на базе электронного меню</h3>
        </div>

        <div class="gear-content" id="about-gear-2">
            <h2>Терминал менеджера</h2>
            <h3>контроль зала</h3>
        </div>

        <div class="gear-content" id="about-gear-3">
            <h2>Терминалы для заказа с собой</h2>
            <h3>для кофеен</h3>
        </div>

        <div class="gear-content" id="about-gear-4">
            <h2>Кухонная<br>дисплейная система</h2>
            <h3>контроль кухни</h3>
        </div>

        <!-- Right -->

        <div class="gear-content" id="about-gear-5">
            <h2>Цифровые вывески</h2>
            <h3>меню на экранах за кассой</h3>
        </div>

        <div class="gear-content" id="about-gear-6">
            <h2>Мобильное<br>приложениедля посетителей</h2>
        </div>

        <div class="gear-content" id="about-gear-7">
            <h2>Терминал официанта</h2>
            <h3>контроль заказов</h3>
        </div>

        <div class="gear-content" id="about-gear-8">
            <h2>Система оплаты через QR-код</h2>
            <h3>в сотрудничестве с payQR</h3>
        </div>

    </div>

</div>

{{ footer_content }}
{{ footer }}

templates/index.html
{% load humanize %}
{{ header }}

<div class="full-size-wrapper">

{{ menu }}

<div class="top-parralax-wrapper">
    <div class="top-parralax-bg parallax-background" parallax-ratio="0.4"></div>
</div>

<div class="bg"></div>
<div class="black-bg"></div>

<!-- Section 1 -->

<div id="section-1">

    <div class="container">

        <div class="row">

            <!-- Left column -->

            <div class="col-xs-7 left">
                <h1>{{ content.section1_header }}</h1>
                <ul>
                    {% if content.section1_q1 %} <li>{{ content.section1_q1 }}</li>{% endif %}
                    {% if content.section1_q2 %} <li>{{ content.section1_q2 }}</li>{% endif %}
                    {% if content.section1_q3 %} <li>{{ content.section1_q3 }}</li>{% endif %}
                </ul>

                <p>{{ content.section1_promo|linebreaksbr }}</p>

                <!--<h2>Уникальная возможность от компании MENUFORYOU</h2>
                <h3>ПРИ ЗАКЛЮЧЕНИИ ДОГОВОРА ДО 30 НОЯБРЯ<br>МЕСЯЦ ОБСЛУЖИВАНИЯ БЕСПЛАТНО</h3>-->
            </div>

            <!-- Right column -->

            <div class="col-xs-5 right">

                <div class="card">
                    <h2>Оставить заявку</h2>
                    <p class="p-1">Наши специалисты свяжутся с вами в течение 10 минут</p>
                    <div class="divider"></div>
                    <h3>Автоматизация ресторана</h3>
                    <p class="p-2">ОТ {{ content.price|intcomma }} <span>руб/месяц</span></p>
                    <div class="divider"></div>
                    <form class="form-container feedback-form">
                        {% csrf_token %}
                        <h3>Ваше имя</h3>
                        <input type="text" name="name" placeholder="Имя">
                        <h3>Ваш адрес электронной почты</h3>
                        <input type="email" name="email" placeholder="E-mail">
                        <h3>Ваш телефон</h3>
                        <table><tr>
                            <td id="fbf-col-1">+7</td>
                            <td id="fbf-col-2"><input type="text" id="feedback-form-phone-code" maxlength="3" placeholder="123" name="phone_code"></td>
                            <td><input type="text" id="feedback-form-phone-number" placeholder="4567890" maxlength="7" name="phone_number"></td>
                        </tr></table>

                        <input type="submit" class="btn-submit-request" value="Отправить заявку">
                        <input type="hidden" name="form_name" value="Оставить завяку">
                        <input type="hidden" name="page" value="1">

                        <div class="results">
                            <img src="/static/mainapp/img/loading.gif" class="loading">
                            <div class="message"></div>
                        </div>
                    </form>
                </div>

            </div>

        </div>

        <div class="footer">

            <h2 class="dotted-line-header">Владельцам и управляющим ресторана</h2>
            <p>{{ content.section1_footer|linebreaksbr }}</p>

        </div>

    </div>

</div>

<div class="top-parralax-wrapper s2">
    <div class="top-parralax-bg parallax-background" parallax-ratio="0.4"></div>
</div>

<!-- Section 2 -->

<div class="tape-section" id="section-2">
    <a href="/projects/mobile-terminal/" class="go"></a>

    <div class="left-tape"></div>
    <div class="right-tape"></div>
    <div class="seam-tape"></div>

    <div class="container">

        <div class="row">

            <div class="col-xs-6 left">
                <h2>МОБИЛЬНЫЙ ТЕРМИНАЛ<br>МЕНЕДЖЕРА</h2>
                <h3>MOBILE MANAGER TERMINAL</h3>
                <p>{{ content.section2_l_text|linebreaksbr }}</p>
                <div class="platforms">доступен на платформах</div>
                <div class="platform-icon ios"></div>
                <div class="platform-icon android"></div>
                <div class="illustration"></div>
            </div>

            <div class="col-xs-6 right">
                <h2>ЛИЧНЫЙ КАБИНЕТ<br>РЕСТОРАТОРА</h2>
                <h3>Restaurateur MEMBERS AREA</h3>
                <p>{{ content.section2_r_text|linebreaksbr }}</p>
                <div class="illustration"></div>
            </div>

        </div>

        <div class="footer">

            <h2 class="dotted-line-header">менеджерам ресторана</h2>
            <p>{{ content.section2_footer|linebreaksbr }}</p>

        </div>

    </div>

</div>

<!-- Section 3 -->

<div class="tape-section" id="section-3">
    <a href="/projects/waiter-terminal/" class="go"></a>

    <div class="left-tape"></div>
    <div class="right-tape"></div>
    <div class="seam-tape"></div>

    <div class="container">

        <div class="row">

            <div class="col-xs-6 left">
                <h2>МОБИЛЬНЫЙ ТЕРМИНАЛ<br>ОФИЦИАНТА</h2>
                <h3>MOBILE WAITER TERMINAL</h3>
                <p>{{ content.section3_l_text|linebreaksbr }}</p>
                <div class="platforms">доступен на платформах</div>
                <div class="platform-icon ios"></div>
                <div class="platform-icon android"></div>
                <div class="illustration"></div>
            </div>

            <div class="col-xs-6 right">
                <h2>КУХОННАЯ ДИСПЛЕЙНАЯ<br>СИСТЕМА</h2>
                <h3>KITCHEN DISPLAY SYSTEM</h3>
                <p>{{ content.section3_r_text|linebreaksbr }}</p>
                <div class="illustration"></div>
            </div>

        </div>

        <div class="footer">

            <h2 class="dotted-line-header">новые каналы продаж</h2>
            <p>{{ content.section3_footer|linebreaksbr }}</p>

        </div>

    </div>

</div>

<!-- Section 4 -->

<div class="tape-section" id="section-4">
    <a href="/projects/mobile-menu/" class="go"></a>

    <div class="left-tape"></div>
    <div class="right-tape"></div>

    <div class="container">

        <div class="row">

            <div class="col-xs-4 left">
                <h2>МЕНЮ НА ПЛАНШЕТЕ</h2>
                <h3>ELECTRONIC MENU</h3>
            </div>

            <div class="col-xs-4 center">
                <h2>ПРИЛОЖЕНИЕ<br>ДЛЯ ГОСТЕЙ</h2>
                <h3>MOBILE APPLICTATION<br>FOR GUESTS</h3>

                <div class="platfoms-block">
                    <div class="platforms">доступен на платформах</div>
                    <div class="clearfix"></div>
                    <div class="platform-icon ios"></div>
                    <div class="platform-icon android"></div>
                </div>
            </div>

            <div class="col-xs-4 right">
                <h2>СЕРВИС ДОСТАВКИ</h2>
                <h3>DELIVERY SERVICE</h3>
            </div>

        </div>

    </div>

</div>

<!-- Feedback -->

<div class="feedback">
    {{ feedback_form }}
</div>

<!-- Video -->

<div class="container video">
    <h4 class="dotted-line-header">ВИДЕО</h4>
    <div>
        <iframe width="100%" height="540" src="{{ content.video_url }}" frameborder="0" allowfullscreen></iframe>
    </div>
</div>

<!-- Our Team -->

<div class="container our-team">
    <h2 class="dotted-line-header">НАША КОМАНДА</h4>
    <h3>{{ content.team_header }}</h2>
    <h4>{{ content.team_text|linebreaksbr }}</h3>

    {{ team }}
</div>

</div>

{{ footer_content }}
{{ footer }}

templates/mobile_menu.html
{% load humanize %}
{% load thumbnail %}

{{ header }}

<div id="loader-wrapper">
    <div id="loader"></div>

    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>
</div>

{{ menu }}

<div id="mobile_menu">

    <div class="section" id="slide-1" index="1">
        <div class="bg parallax" parallax-ratio="1" slide="#slide-1"></div>

        <h1>Продавай не меню,<br>а настроение</h1>
        <div class="tablet"></div>
        <a href="#" id="read-more" class="info-btn">Узнать больше</a>

    </div>

    <div class="section" id="slide-2" index="2">
        <h2>Новая реальность</h2>
        <h3>Меню - это не список боюд, а инструмент их продажи</h3>

        <div class="illustration"></div>

        <div class="container">
            <div class="row">
                <div class="col-xs-6">
                    <ul>
                        <li data-icon="1">бесполезная бумага</li>
                        <li data-icon="1">бесполезная бумага</li>
                        <li data-icon="1">бесполезная бумага</li>
                        <li data-icon="1">бесполезная бумага</li>
                        <li data-icon="1">по прежнему бесполезная бумага</li>
                    </ul>
                </div>
                <div class="col-xs-6">
                    <ul>
                        <li data-icon="2">повышение среднего чека на 20%</li>
                        <li data-icon="3">уменьшение ticket time на 25%</li>
                        <li data-icon="4">система рекомендация</li>
                        <li data-icon="5">рекламная площадка</li>
                        <li data-icon="6">огромный потенциал для дальнейшего развития</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="section" id="slide-3" index="3">
        <h2>Эволюция сервиса</h2>
        <h3>Мы открываем для ресторанов новую эпоху</h3>
        <div class="illustration"></div>
        <h4>А где Вы?</h4>
    </div>

    <div class="section" id="slide-4" index="4">
        <h2>Лучше один раз увидеть</h2>

        <div id="gallery">

            <div id="gallery-slick">

                {% for slide in content.tabletslide_set.all %}


                    <div class="illustration">
                        {% thumbnail slide.image "616x384" crop="center" as im %}
                            <div class="photo" style="background: url('{{ im.url }}'); background-size: cover;"></div>
                        {% endthumbnail %}

                        <div class="tablet"></div>
                        <div class="hint-wrapper">
                            <div class="hint">
                                <h3>{{ slide.header }}</h3>
                                <p>{{ slide.text|linebreaksbr }}</p>
                            </div>
                        </div>
                    </div>

                {% endfor %}

            </div>

        </div>
    </div>

    <div class="section" id="slide-5" index="4">
        <h2>Лучше один раз увидеть</h2>
        <iframe width="960" height="500" src="{{ content.video_url }}" frameborder="0" allowfullscreen></iframe>
    </div>

    <!-- footer slides -->

    <div class="section" id="slide-6" index="6">
        <div class="bg parallax" parallax-ratio="1" slide="#slide-6"></div>
        <div class="feedback">
            <h3 class = "slide-header">Заставь меню работать</h3>

            <center><div class = "price-wrapper">
                <div class = "price">Всего за</div><strong class = "price">{{ content.price|intcomma }} руб/месяц</strong>
            </div></center>

            {{ feedback_form }}
        </div>

    </div>

    <!-- Footer -->

    <div class="section" id="slide-7" index="7">
        {{ footer_content }}
    </div>

</div>

{{footer}}

templates/mobile_terminal.html
{% load humanize %}

{{ header }}

<div id="loader-wrapper">
    <div id="loader"></div>

    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>
</div>

{{ menu }}

<div class="phone-absolute hide" begin="2" end = "5"></div>
<div id="mobile_terminal">

    <div class="section" id="slide-1" index="1">
        <div class = "bg parallax" parallax-ratio="0.4" slide="#slide-1"></div>

        <div class = "content-wrapper">
            <h1>Мобильный терминал менеджера</h1>
            <h3>Совершенно новый способ контроля официантов</h3>
            <a href="#" id="read-more" class="info-btn">Узнать больше</a>
        </div>
    </div>

    <!-- mobile slides -->

    <div class="section phone-section" id="slide-2" index="2">
        <div class="bg parallax" parallax-ratio="0.4" slide="#slide-2"></div>

        <div class="illustration">
            <div class="illustration-wrapper">
                <div class="parallax-phone phone leave" slide="#slide-2"></div>
            </div>
        </div>

        <div class="content-wrapper">
            <h2>{{ content.screen1_header }}</h2>
            <p>{{ content.screen1_text|linebreaksbr }}</p>
        </div>
    </div>

    <div class="section phone-section" id="slide-3" index="3">
        <div class="bg"></div>

        <div class="illustration">
            <div class="illustration-wrapper">

            </div>
        </div>

        <div class="content-wrapper">
            <h2>{{ content.screen2_header }}</h2>
            <p>{{ content.screen2_text|linebreaksbr }}</p>
        </div>
    </div>

    <div class="section phone-section" id="slide-4" index="4">
        <div class="bg parallax" parallax-ratio="0.4" slide="#slide-4"></div>

        <div class="illustration">
            <div class="illustration-wrapper">

            </div>
        </div>

        <div class="content-wrapper">
            <h2>{{ content.screen3_header }}</h2>
            <p>{{ content.screen3_text|linebreaksbr }}</p>
        </div>
    </div>

    <div class="section phone-section" id="slide-5" index="5">
        <div class="bg"></div>

        <div class="illustration">
            <div class="illustration-wrapper">
                <div class="phone last" slide="#slide-5"></div>
            </div>
        </div>

        <div class="content-wrapper">
            <h2>{{ content.screen4_header }}</h2>
            <p>{{ content.screen4_text|linebreaksbr }}</p>
        </div>
    </div>

    <!-- footer slides -->

    <div class="section" id="slide-6" index="6">
        <div class="bg parallax" parallax-ratio="0.4" slide="#slide-6"></div>
        <div class="feedback">
            <h3 class = "slide-header">Прекрасное средство оперативного контроля официантов в любой точке ресторана.</h3>

            <center><div class = "price-wrapper">
                <div class = "price">Всего за</div><strong class = "price">{{ content.price|intcomma }} руб/месяц</strong>
            </div></center>

            {{ feedback_form }}
        </div>

    </div>

    <!-- Footer -->

    <div class="section" id="slide-7" index="7">
        {{ footer_content }}
    </div>

</div>

{{footer}}

templates/waiter_terminal.html
{% load humanize %}
{% load thumbnail %}

{{ header }}

<div id="loader-wrapper">
    <div id="loader"></div>

    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>
</div>

{{ menu }}

<div id="waiter_terminal">

    <div class="section" id="slide-1" index="1">
        <div class="bg parallax" parallax-ratio="0.4" slide="#slide-1"></div>

        <div class="container relative">
            <div class="hand"></div>
            <div class="row relative">

                <div class="col-xs-6"></div>
                <div class="col-xs-6 relative">
                    <div class="content">
                        <h1>Мобильный терминал официанта</h1>
                        <h3>Мы делаем официантов лучше</h3>
                        <a href="#" id="read-more" class="info-btn">Узнать больше</a>
                    </div>
                </div>

            </div>
        </div>

    </div>

    <div class="section" id="slide-2" index="2">
        <div class="wrapper">
            <div class="container">
                <div class="row">
                    <div class="col-xs-6">
                        <div class="waiter"></div>
                        <div class = "content">
                            <h2>{{ content.screen1_header }}</h2>
                            <h3>{{ content.screen1_quote|linebreaksbr }}</h3>
                            <p>{{ content.screen1_u_quote|linebreaksbr }}</p>
                            <h4>{{ content.screen1_text|linebreaksbr }}</h4>
                        </div>
                    </div>

                    <div class="col-xs-6">
                        <div class="phone leave"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="section" id="slide-3" index="3">

        <div class="relative">
            <div class="phone-2"></div>
        </div>

        <div id="gallery-slick">

            {% for slide in content.waiterslide_set.all %}

                <div class="illustration">
                    <div class="phone">
                        {% thumbnail slide.image "153x270" crop="center" quality=65 as im %}
                            <div class="image" style="background: url('{{ im.url }}'); background-size: cover;"></div>
                        {% endthumbnail %}
                    </div>

                    <div class="container">
                        <h3>{{ slide.header }}</h3>
                        <p>{{ slide.text|linebreaksbr }}<p>
                    </div>

                </div>

            {% endfor %}

        </div>

    </div>

    <div class="section" id="slide-4" index="4">
        <div class="container">
            <h2>Лучше один раз увидеть</h2>
            <iframe width="960" height="500" src="{{ content.video_url }}" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>

    <!-- footer slides -->

    <div class="section" id="slide-5" index="5">
        <div class="bg parallax" parallax-ratio="0.4" slide="#slide-5"></div>
        <div class="feedback">
            <h3 class = "slide-header">Прекрасное средство оперативного контроля официантов в любой точке ресторана.</h3>

            <center><div class = "price-wrapper">
                <div class = "price">Всего за</div><strong class = "price">{{ content.price|intcomma }} руб/месяц</strong>
            </div></center>

            {{ feedback_form }}
        </div>

    </div>

    <!-- Footer -->

    <div class="section" id="slide-6" index="6">
        {{ footer_content }}
    </div>

</div>

{{footer}}